### ISSUE TITLE
De-debug collection in Profile view

### ISSUE THREAD

**Issue by crosssenses** [pankegallery/openar#27]
Once the collection is running, make the following changes to #1 

In u/[eth] and /x/:

- [x]  change `hasCollection = true/false` to `hasCollection = userProfileRead?.artworks.length > 0;`
- [x]  replace artworks with collection in `<CollectionList artworks={userProfileRead.collection} … />`
- [x]  Check if collection works…

**Comment by novazembla** [comment]
Done
